# environment must be either 'development' or 'production'
environment: development
server:
  port: 8180 # What port do you want YAAM to listen on
  host: 0.0.0.0 # What Ip Address do you want nodeSDR to listen on. Use 0.0.0.0 for all IP addresses
# It is recommended to make this as random and long as possible as it will be used for hashing passwords in the database.
# To generate a good random string, on a Linux terminal run the following command
# cat /dev/urandom | tr -dc '[:alpha:]' | fold -w ${1:-20} | head -n 1
salt_secret: 'BgbUFvZWqSkkxqhklVDO'
secret: "This is a secret passphrase"
